CREATE TABLE NhanVien(
	id NVARCHAR(50) PRIMARY KEY,
	username NVARCHAR(255) NULL,
	email NVARCHAR(100) UNIQUE NOT NULL,
	gioiTinh NVARCHAR(10),
	password NVARCHAR(255) NULL,
	profile_img NVARCHAR(255) NULL,
	date_signup DATE NULL
)

CREATE TABLE QuanLy (
    id NVARCHAR(50) PRIMARY KEY,
    username NVARCHAR(50) NOT NULL,
    email NVARCHAR(100) UNIQUE NOT NULL,
    password NVARCHAR(255) NOT NULL
)
